"""Refactor repository

Revision ID: 96485a9df9c7
Revises: 
Create Date: 2026-02-02 19:49:29.426731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96485a9df9c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'grounds', ['name_en'])
    op.create_foreign_key(None, 'match_stats', 'matches', ['match_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key(None, 'player_championship_association', 'players', ['player_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.alter_column('teams', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'icon_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'player_championship_association', type_='foreignkey')
    op.drop_constraint(None, 'match_stats', type_='foreignkey')
    op.drop_constraint(None, 'grounds', type_='unique')
    # ### end Alembic commands ###
